package output

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/ButtersesHouse/Chalmuns/internal/state"
)

const maxCLAUDERules = 30

// staleAfterPRs is how far behind the PR watermark a rule's last_seen_pr may
// fall before its rendered source line asks the reader to re-verify it. Keep
// in sync with the "Stale rules" threshold in SKILL.md Step 13.
const staleAfterPRs = 200

// UniversalLocation is the Target.Location sentinel meaning "this rule applies
// to every file in the repo". It is spelled "CLAUDE.md" for backward
// compatibility with existing state.json files written before universal rules
// had a skill of their own; nothing is written to a file by that name.
const UniversalLocation = "CLAUDE.md"

// UniversalSkillName is the domain directory universal rules are generated
// into. They get a real skill like every other rule rather than a repo-root
// file, and it carries no `paths:` gate so it auto-loads everywhere.
const UniversalSkillName = "conventions"

// GeneratedMarker is the first body line of every SKILL.md this package
// writes. It tells readers the file is regenerated from state, and it is how
// Write recognises a skill directory as its own when a domain disappears from
// state (renamed, merged, or every rule rejected): a directory whose SKILL.md
// carries this exact line is pruned, anything else under the skills root is
// left alone. The match is on the whole line, not a substring, so a
// hand-written skill that merely mentions pattern-learner is never touched.
const GeneratedMarker = "<!-- Generated by pattern-learner (write-outputs). Do not edit: this directory is regenerated from .claude/pattern-learner/state.json on every run. -->"

// Options controls optional output features.
type Options struct {
	// RAGHints adds a cursor-agent query hint after each rule in domain skill
	// files so the AI can retrieve live codebase examples at skill-use time.
	RAGHints bool
	// SkillsDir is the explicit destination directory for per-domain skill
	// files. When empty, defaults to <outputDir>/.claude/skills.
	SkillsDir string
}

// Write generates the per-domain skill files under opts.SkillsDir (default
// <outputDir>/.claude/skills).
//
// Write deliberately touches nothing above the skills directory. That tree is
// generator-owned and safe to regenerate wholesale; a repo-root instruction
// file (AGENTS.md, CLAUDE.md) is hand-maintained and lives in the user's git
// history, so publishing to it is an explicit, user-initiated step — see
// Promote.
func Write(s state.State, outputDir string, opts Options) error {
	skillsDir := opts.SkillsDir
	if skillsDir == "" {
		skillsDir = filepath.Join(outputDir, ".claude", "skills")
	}
	return writeSkillFiles(s, skillsDir, opts)
}

// renderUniversalRules writes CLAUDE.md-targeted rules at the given heading level.
func renderUniversalRules(b *strings.Builder, rules []state.Rule, heading string) {
	for _, r := range rules {
		b.WriteString(fmt.Sprintf("%s %s\n\n", heading, r.Title))
		renderExamples(b, r, 1)
		b.WriteString(r.Rule + "\n\n")
		b.WriteString(fmt.Sprintf("_Source: %s_\n\n", sourceLabel(r)))
	}
}

func dedupeStrings(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if s != "" && !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// writeSkillFiles writes per-domain skill files under skillsDir.
// skillsDir is the root under which per-domain subdirs are created (e.g.
// ".claude/skills" → ".claude/skills/api/SKILL.md").
func writeSkillFiles(s state.State, skillsDir string, opts Options) error {
	byDomain := map[string][]state.Rule{}
	var universal []state.Rule
	for _, r := range s.Rules {
		if r.Status != "approved" || r.Target.Location == "" {
			continue
		}
		if r.Target.Location == UniversalLocation {
			universal = append(universal, r)
			continue
		}
		byDomain[r.Target.Location] = append(byDomain[r.Target.Location], r)
	}

	// Universal rules are a skill too. If a scoped domain happens to already
	// be called "conventions", the two merge into that one skill — and
	// writeSkillFile drops its paths gate, since gating a file that carries
	// repo-wide rules behind a glob would hide them on every other file.
	if len(universal) > 0 {
		byDomain[UniversalSkillName] = append(universal, byDomain[UniversalSkillName]...)
	}

	// Validate every domain before touching the tree, so a bad name fails the
	// run with nothing written rather than after a map-ordered subset.
	byFold := map[string]string{}
	for domain := range byDomain {
		if !validDomain(domain) {
			return fmt.Errorf("skill domain %q is not a valid directory name; re-target its rules to a single-segment domain (e.g. \"api\") and rerun", domain)
		}
		// Two domains differing only by case share one directory on a
		// case-insensitive filesystem, and the second write would wipe the
		// first's examples/ and rules/. Refuse rather than lose rules.
		folded := strings.ToLower(domain)
		if other, dup := byFold[folded]; dup {
			return fmt.Errorf("skill domains %q and %q differ only by case and would share one directory; merge them into a single domain and rerun", other, domain)
		}
		byFold[folded] = domain
	}

	// Prune before writing. Pruning afterwards would, on a case-insensitive
	// filesystem, see the directory just written under its old casing
	// ("Api" for domain "api"), miss it in the live set, and delete it.
	if err := pruneStaleSkills(skillsDir, byDomain); err != nil {
		return err
	}
	for domain, rules := range byDomain {
		if err := writeSkillFile(domain, rules, skillsDir, s.DomainDescriptions[domain], s.LastExtractedPRNumber, opts); err != nil {
			return err
		}
	}
	return nil
}

// pruneStaleSkills removes generated skill directories under skillsDir whose
// domain no longer has approved rules. Without this, a renamed or merged
// domain (or one whose rules were all rejected) leaves its old SKILL.md
// behind, and the consuming agent keeps auto-loading conventions that state
// no longer holds. Only directories whose SKILL.md this generator wrote
// (see isGeneratedSkill) are candidates; hand-authored skills sharing the
// root are never removed.
func pruneStaleSkills(skillsDir string, live map[string][]state.Rule) error {
	entries, err := os.ReadDir(skillsDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, ok := live[e.Name()]; ok {
			continue
		}
		dir := filepath.Join(skillsDir, e.Name())
		if !isGeneratedSkill(filepath.Join(dir, "SKILL.md"), e.Name()) {
			continue
		}
		if err := os.RemoveAll(dir); err != nil {
			return err
		}
	}
	return nil
}

// generatedBodyLines are fixed sentences the generator writes into a skill
// body. They identify a skill from a build that predates GeneratedMarker
// (the first two since the progressive-disclosure layout, the third for
// longer), which is the population pruning was added to clean up. Each is
// long and exact, so a hand-written skill cannot match by accident. A skill
// from a build older than all three carries no fingerprint and must be
// removed by hand; SKILL.md says so.
var generatedBodyLines = []string{
	"Rules with examples link a file under `examples/` — read it at your discretion for do/don't code and real instances before writing code the rule covers.",
	"This skill is chunked to keep SKILL.md small: each rule lives in its own file under `rules/`, examples included. Find matching rules in the index below (by title or glob) and read only those files. For a full-text lookup, grep the `rules/` directory next to this file, e.g. `grep -ril \"<keyword>\" rules/`.",
	"Read one of these before writing new code in this domain — they best represent the team's style:",
}

var reFrontmatterName = regexp.MustCompile(`(?m)^name:\s*(.+?)\s*$`)

// isGeneratedSkill reports whether the SKILL.md at path is one this package
// wrote for the skill directory dirName. Two conditions must both hold:
//
//   - the frontmatter name equals dirName, so a generated skill a user
//     copied elsewhere and adopted ("api-style/" carrying name "api") is not
//     mistaken for the generator's own output; and
//   - the body carries GeneratedMarker or, for a file from a build that
//     predates the marker, one of generatedBodyLines as a whole line.
//
// A generated skill kept under its original directory name and hand-edited
// is still recognised: that directory is documented as generator-owned and
// regenerated wholesale, so its edits were never safe.
func isGeneratedSkill(path, dirName string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	content := string(data)
	m := reFrontmatterName.FindStringSubmatch(content)
	if m == nil {
		return false
	}
	name := strings.Trim(m[1], `"'`)
	if name != dirName {
		return false
	}
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == GeneratedMarker {
			return true
		}
		for _, generated := range generatedBodyLines {
			if line == generated {
				return true
			}
		}
	}
	return false
}

func writeSkillFile(domain string, rules []state.Rule, skillsDir string, override string, watermark int, opts Options) error {
	sort.Slice(rules, func(i, j int) bool {
		ri, rj := confidenceRank(rules[i].Confidence), confidenceRank(rules[j].Confidence)
		if ri != rj {
			return ri < rj
		}
		return rules[i].Title < rules[j].Title
	})

	globs := collectGlobs(rules)
	if domain == UniversalSkillName {
		// No paths gate: these rules apply to every file, so the skill must
		// auto-load regardless of what is being edited.
		globs = nil
	}
	desc := buildDescription(domain, globs, override)
	skillDir := filepath.Join(skillsDir, domain)

	// examples/ and rules/ are generator-owned: regenerate from scratch so
	// renamed or removed rules leave no stale files behind.
	for _, sub := range []string{"examples", "rules"} {
		if err := os.RemoveAll(filepath.Join(skillDir, sub)); err != nil {
			return err
		}
	}

	slugs := ruleSlugs(rules)
	header := renderSkillHeader(domain, desc, globs, rules)

	// Examples always live in companion files (progressive disclosure): the
	// SKILL.md body is a recurring token cost once loaded, so it carries only
	// the imperative rules plus pointers the consuming agent follows at its
	// discretion when it wants the do/don't code.
	inline := header + renderInlineRules(rules, slugs, watermark, opts)
	if lineCount(inline) <= maxSkillLines {
		if err := writeExampleFiles(skillDir, rules, slugs); err != nil {
			return err
		}
		return atomicWrite(filepath.Join(skillDir, "SKILL.md"), inline)
	}

	// Very large skill: chunk per the Claude Code guidance ("Keep SKILL.md
	// under 500 lines. Move detailed reference material to separate files.").
	// SKILL.md becomes a rule index; each rule lives in rules/<slug>.md with
	// its examples inline (the chunk itself is loaded on demand), and the
	// chunk corpus doubles as a grep target for full-text lookup.
	if err := writeRuleChunks(skillDir, rules, slugs, watermark, opts); err != nil {
		return err
	}
	return atomicWrite(filepath.Join(skillDir, "SKILL.md"), header+renderRuleIndex(rules, slugs))
}

// maxSkillLines is the chunking threshold for a generated domain SKILL.md,
// with headroom under the documented limit ("Keep SKILL.md under 500 lines").
const maxSkillLines = 450

// maxExamplePairs caps rendered do/don't pairs; state caps the arrays at 4.
const maxExamplePairs = 4

func renderSkillHeader(domain, desc string, globs []string, rules []state.Rule) string {
	var b strings.Builder
	// Every value is emitted as a double-quoted YAML scalar. Claude Code
	// parses this block as real YAML, and unquoted values break in exactly
	// the shapes this generator produces: a description containing ": "
	// ("Conventions for HTTP API endpoints: error responses, ...") is a
	// mapping-value error, and a glob starting with "*" ("*.tsx", "**/*.go")
	// is read as an alias. Either makes the whole skill fail to load.
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("name: %s\n", yamlQuote(domain)))
	b.WriteString(fmt.Sprintf("description: %s\n", yamlQuote(desc)))
	// paths gates auto-loading to work on matching files, so chain-loading
	// several domain skills only ever pulls in the ones actually in play.
	// The documented form is one quoted comma-separated string.
	if len(globs) > 0 {
		b.WriteString(fmt.Sprintf("paths: %s\n", yamlQuote(strings.Join(globs, ","))))
	}
	b.WriteString("---\n\n")
	b.WriteString(GeneratedMarker + "\n\n")
	// "conventions" is already the noun, so don't render "Conventions Conventions".
	if domain == UniversalSkillName {
		b.WriteString("# Repo-Wide Conventions\n\n")
		b.WriteString("These rules apply to every file in this repository, regardless of what you are editing.\n\n")
	} else {
		b.WriteString(fmt.Sprintf("# %s Conventions\n\n", headingTitle(domain)))
	}

	if exemplary := exemplaryFiles(rules); len(exemplary) > 0 {
		b.WriteString("## Exemplary Files\n\n")
		b.WriteString("Read one of these before writing new code in this domain — they best represent the team's style:\n\n")
		for _, f := range exemplary {
			b.WriteString(fmt.Sprintf("- `%s`\n", f))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderInlineRules(rules []state.Rule, slugs []string, watermark int, opts Options) string {
	var b strings.Builder
	b.WriteString("## Rules\n\n")
	b.WriteString("Rules with examples link a file under `examples/` — read it at your discretion for do/don't code and real instances before writing code the rule covers.\n\n")
	for i, r := range rules {
		b.WriteString(fmt.Sprintf("### %s\n\n", r.Title))
		b.WriteString(r.Rule + "\n\n")
		if hasExamples(r) {
			b.WriteString(fmt.Sprintf("_Examples: `examples/%s.md`_\n\n", slugs[i]))
		}
		writeSourceLine(&b, r, watermark)
		writeRAGHint(&b, r, opts)
	}
	return b.String()
}

// writeExampleFiles writes one examples/<slug>.md per rule that has examples,
// holding every do/don't pair plus real-instance refs.
func writeExampleFiles(skillDir string, rules []state.Rule, slugs []string) error {
	for i, r := range rules {
		if !hasExamples(r) {
			continue
		}
		var b strings.Builder
		b.WriteString(fmt.Sprintf("# Examples — %s\n\n", r.Title))
		b.WriteString(r.Rule + "\n\n")
		renderExamples(&b, r, maxExamplePairs)
		if err := atomicWrite(filepath.Join(skillDir, "examples", slugs[i]+".md"), b.String()); err != nil {
			return err
		}
	}
	return nil
}

// writeRuleChunks writes one rules/<slug>.md per rule for the chunked layout.
func writeRuleChunks(skillDir string, rules []state.Rule, slugs []string, watermark int, opts Options) error {
	for i, r := range rules {
		var b strings.Builder
		b.WriteString(fmt.Sprintf("# %s\n\n", r.Title))
		meta := fmt.Sprintf("**Confidence:** %s", r.Confidence)
		if len(r.Target.FileGlob) > 0 {
			meta += " · **Applies to:** `" + strings.Join(r.Target.FileGlob, "`, `") + "`"
		}
		b.WriteString(meta + "\n\n")
		renderExamples(&b, r, maxExamplePairs)
		b.WriteString(r.Rule + "\n\n")
		writeSourceLine(&b, r, watermark)
		writeRAGHint(&b, r, opts)
		if err := atomicWrite(filepath.Join(skillDir, "rules", slugs[i]+".md"), b.String()); err != nil {
			return err
		}
	}
	return nil
}

func renderRuleIndex(rules []state.Rule, slugs []string) string {
	var b strings.Builder
	b.WriteString("This skill is chunked to keep SKILL.md small: each rule lives in its own file under `rules/`, examples included. Find matching rules in the index below (by title or glob) and read only those files. For a full-text lookup, grep the `rules/` directory next to this file, e.g. `grep -ril \"<keyword>\" rules/`.\n\n")
	b.WriteString("## Rule Index\n\n")
	last := ""
	for i, r := range rules {
		if r.Confidence != last {
			b.WriteString(fmt.Sprintf("### %s\n\n", confidenceHeading(r.Confidence)))
			last = r.Confidence
		}
		line := fmt.Sprintf("- [%s](rules/%s.md)", r.Title, slugs[i])
		if len(r.Target.FileGlob) > 0 {
			line += " — `" + strings.Join(r.Target.FileGlob, "`, `") + "`"
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
	return b.String()
}

func confidenceHeading(c string) string {
	switch c {
	case "stated":
		return "Stated (explicit preferences)"
	case "established":
		return "Established"
	case "emerging":
		return "Emerging"
	default:
		return capitalize(c)
	}
}

func writeSourceLine(b *strings.Builder, r state.Rule, watermark int) {
	prOrigin := r.Origin == "" || r.Origin == "pr-review"
	if prOrigin && watermark > 0 && r.LastSeenPR > 0 && watermark-r.LastSeenPR >= staleAfterPRs {
		b.WriteString(fmt.Sprintf("_Source: %s_ _(last seen: PR #%d — verify this convention is still current)_\n\n",
			sourceLabel(r), r.LastSeenPR))
		return
	}
	b.WriteString(fmt.Sprintf("_Source: %s_\n\n", sourceLabel(r)))
}

// ragHintTitle prepares a rule title for the RAG hint, which is a shell
// command inside a markdown code span that the agent may paste verbatim.
// Quotes, backslashes and dollars are escaped for the shell; backticks are
// dropped because a code span cannot contain one (backslash escapes do not
// apply inside spans), and the title reads fine without them.
var ragHintTitle = strings.NewReplacer(`\`, `\\`, `"`, `\"`, "$", `\$`, "`", "")

func writeRAGHint(b *strings.Builder, r state.Rule, opts Options) {
	if !opts.RAGHints {
		return
	}
	b.WriteString(fmt.Sprintf(
		"_Live examples: `cursor-agent -p --mode=ask \"Show me 3 real examples of '%s' in this codebase with file paths\"`_\n\n",
		ragHintTitle.Replace(r.Title),
	))
}

func hasExamples(r state.Rule) bool {
	return len(effectiveDoExamples(r)) > 0 || len(effectiveDontExamples(r)) > 0
}

// slugify converts a rule title to a filesystem-safe slug.
func slugify(title string) string {
	var out []rune
	lastDash := true // also trims leading dashes
	for _, r := range strings.ToLower(title) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			out = append(out, r)
			lastDash = false
		} else if !lastDash {
			out = append(out, '-')
			lastDash = true
		}
	}
	s := strings.Trim(string(out), "-")
	if len(s) > 60 {
		s = strings.Trim(s[:60], "-")
	}
	if s == "" {
		return "rule"
	}
	return s
}

// ruleSlugs returns one unique slug per rule (suffixing -2, -3, … on collision).
func ruleSlugs(rules []state.Rule) []string {
	seen := map[string]int{}
	out := make([]string, len(rules))
	for i, r := range rules {
		s := slugify(r.Title)
		seen[s]++
		if n := seen[s]; n > 1 {
			s = fmt.Sprintf("%s-%d", s, n)
		}
		out[i] = s
	}
	return out
}

func lineCount(s string) int {
	return strings.Count(s, "\n") + 1
}

// renderExamples writes do/don't example pairs (up to maxPairs) before rule prose.
// Prefers DoExamples/DontExamples (plural); falls back to DoExample/DontExample for
// rules created before plural support was added.
func renderExamples(b *strings.Builder, r state.Rule, maxPairs int) {
	dos := effectiveDoExamples(r)
	donts := effectiveDontExamples(r)

	if len(dos) == 0 && len(donts) == 0 {
		return
	}

	n := len(dos)
	if len(donts) > n {
		n = len(donts)
	}
	if n > maxPairs {
		n = maxPairs
	}

	for i := 0; i < n; i++ {
		if i < len(dos) {
			b.WriteString(fmt.Sprintf("**Do:**\n```%s\n%s\n```\n", dos[i].Language, dos[i].Code))
			if dos[i].FileRef != "" {
				b.WriteString(fmt.Sprintf("_Real instance: see %s_\n", dos[i].FileRef))
			}
			b.WriteString("\n")
		}
		if i < len(donts) {
			b.WriteString(fmt.Sprintf("**Don't:**\n```%s\n%s\n```\n\n", donts[i].Language, donts[i].Code))
		}
	}
}

func effectiveDoExamples(r state.Rule) []state.Example {
	if len(r.DoExamples) > 0 {
		return r.DoExamples
	}
	if r.DoExample != nil {
		return []state.Example{*r.DoExample}
	}
	return nil
}

func effectiveDontExamples(r state.Rule) []state.Example {
	if len(r.DontExamples) > 0 {
		return r.DontExamples
	}
	if r.DontExample != nil {
		return []state.Example{*r.DontExample}
	}
	return nil
}

// approvedRules returns approved rules for a given target location,
// sorted stated → established → emerging, then alphabetically by title.
func approvedRules(s state.State, location string) []state.Rule {
	var out []state.Rule
	for _, r := range s.Rules {
		if r.Status == "approved" && r.Target.Location == location {
			out = append(out, r)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		ri, rj := confidenceRank(out[i].Confidence), confidenceRank(out[j].Confidence)
		if ri != rj {
			return ri < rj
		}
		return out[i].Title < out[j].Title
	})
	return out
}

// confidenceRank returns the sort priority for a confidence level.
// Lower is higher priority: stated(0) > established(1) > emerging(2).
func confidenceRank(c string) int {
	switch c {
	case "stated":
		return 0
	case "established":
		return 1
	case "emerging":
		return 2
	default:
		return 3
	}
}

// sourceLabel returns the provenance text for a rule's "_Source: …_" line.
// Manual and discover-origin rules have no PR numbers, so they get a descriptive
// label instead of an empty PR list.
func sourceLabel(r state.Rule) string {
	switch r.Origin {
	case "manual":
		return "manually added"
	case "discover":
		return "discovered from codebase"
	default:
		if prs := prList(r.Sources); prs != "" {
			return "PRs " + prs
		}
		return "—"
	}
}

func prList(sources []state.Signal) string {
	seen := map[int]bool{}
	var nums []int
	for _, s := range sources {
		if !seen[s.PRNumber] {
			seen[s.PRNumber] = true
			nums = append(nums, s.PRNumber)
		}
	}
	sort.Ints(nums)
	parts := make([]string, len(nums))
	for i, n := range nums {
		parts[i] = fmt.Sprintf("#%d", n)
	}
	return strings.Join(parts, ", ")
}

// exemplaryFiles returns up to 3 file paths that appear most frequently as
// FileRef targets across the domain's rules. These are the files that best
// represent the domain's coding style and are listed in the skill file so
// the AI can read one for holistic style guidance beyond individual rules.
func exemplaryFiles(rules []state.Rule) []string {
	freq := map[string]int{}
	for _, r := range rules {
		for _, ex := range effectiveDoExamples(r) {
			if ex.FileRef == "" {
				continue
			}
			// Strip :Lline suffix to get the bare file path.
			path := ex.FileRef
			if idx := strings.LastIndex(path, ":L"); idx > 0 {
				path = path[:idx]
			}
			freq[path]++
		}
	}
	if len(freq) == 0 {
		return nil
	}

	type entry struct {
		path  string
		count int
	}
	var entries []entry
	for p, c := range freq {
		entries = append(entries, entry{p, c})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].count != entries[j].count {
			return entries[i].count > entries[j].count
		}
		return entries[i].path < entries[j].path
	})

	max := 3
	if len(entries) < max {
		max = len(entries)
	}
	out := make([]string, max)
	for i := range out {
		out[i] = entries[i].path
	}
	return out
}

func collectGlobs(rules []state.Rule) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range rules {
		for _, g := range r.Target.FileGlob {
			if !seen[g] {
				seen[g] = true
				out = append(out, g)
			}
		}
	}
	return out
}

// buildDescription returns the SKILL.md frontmatter description for a domain.
// If override is non-empty, it is used directly (truncated if needed). Otherwise
// a generic fallback is constructed from the domain name and globs.
func buildDescription(domain string, globs []string, override string) string {
	if override != "" {
		// The override is model-supplied; a newline would break the YAML
		// frontmatter line it is rendered into.
		return truncate(strings.Join(strings.Fields(override), " "), maxDescriptionRunes)
	}
	if domain == UniversalSkillName {
		return "Repo-wide coding conventions extracted from PR review history. Applies to every file; read before writing or reviewing code anywhere in this repository."
	}
	base := fmt.Sprintf("Coding conventions for %s", domain)
	if len(globs) > 0 {
		base += fmt.Sprintf(". Use when editing files matching: %s", strings.Join(globs, ", "))
	}
	return truncate(base, maxDescriptionRunes)
}

// maxDescriptionRunes caps the frontmatter description. Counted in runes,
// not bytes: descriptions routinely carry em dashes and similar multi-byte
// characters, and a byte-indexed cut can split one and leave invalid UTF-8
// in the YAML.
const maxDescriptionRunes = 200

// truncate shortens s to at most max runes, ending in "..." when it cut.
func truncate(s string, max int) string {
	r := []rune(s)
	if len(r) <= max {
		return s
	}
	return strings.TrimRight(string(r[:max-3]), " ") + "..."
}

// validDomain reports whether a domain name can be used as a single skill
// directory segment. Domain names are model-supplied; one containing a path
// separator or "." / ".." would write outside <skillsDir>/<domain>. Charset
// rules (lowercase, digits, hyphens) are the audit-format subcommand's job
// and are deliberately not enforced here.
func validDomain(domain string) bool {
	if domain == "" || domain == "." || domain == ".." {
		return false
	}
	return !strings.ContainsAny(domain, `/\`)
}

// yamlQuote renders s as a YAML double-quoted scalar. It is strconv.Quote:
// every escape Go emits (\a \b \f \n \r \t \v \\ \" \xNN \uNNNN \UNNNNNNNN)
// is also a YAML double-quoted escape, and Go escapes everything that is not
// printable — the C0/C1 controls a YAML parser rejects raw, and the line
// separators (U+0085, U+2028, U+2029) a parser would otherwise fold together
// with adjacent whitespace. Invalid UTF-8 is escaped byte-wise rather than
// passed through.
func yamlQuote(s string) string {
	return strconv.Quote(s)
}

// capitalize upper-cases the first rune of s (not the first byte, which would
// corrupt a leading multi-byte character).
func capitalize(s string) string {
	r, size := utf8.DecodeRuneInString(s)
	if size == 0 || r == utf8.RuneError {
		return s
	}
	return string(unicode.ToUpper(r)) + s[size:]
}

// initialisms maps domain words to their conventional heading spelling.
// Anything not listed is simply capitalized; the list only needs to cover
// the common cases so "Api Conventions" does not read as a typo. Numeronyms
// keep their customary lower-case form.
var initialisms = map[string]string{
	"api": "API", "db": "DB", "sql": "SQL", "http": "HTTP", "rest": "REST", "grpc": "gRPC",
	"rpc": "RPC", "ui": "UI", "ux": "UX", "cli": "CLI", "css": "CSS", "html": "HTML",
	"js": "JS", "ts": "TS", "orm": "ORM", "dto": "DTO", "jwt": "JWT", "sdk": "SDK",
	"ci": "CI", "cd": "CD", "io": "IO", "id": "ID", "sso": "SSO", "oauth": "OAuth",
	"ssr": "SSR", "i18n": "i18n", "l10n": "l10n", "k8s": "k8s", "aws": "AWS", "gcp": "GCP",
}

// headingTitle turns a domain slug into heading text: hyphens and
// underscores become spaces, known initialisms take their conventional
// spelling ("rest-api" → "REST API"), everything else is capitalized
// ("components" → "Components").
func headingTitle(domain string) string {
	words := strings.FieldsFunc(domain, func(r rune) bool { return r == '-' || r == '_' })
	if len(words) == 0 {
		return domain
	}
	for i, w := range words {
		if canonical, ok := initialisms[strings.ToLower(w)]; ok {
			words[i] = canonical
		} else {
			words[i] = capitalize(w)
		}
	}
	return strings.Join(words, " ")
}

func atomicWrite(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
