package output

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/ButtersesHouse/Chalmuns/internal/format"
	"github.com/ButtersesHouse/Chalmuns/internal/state"
)

const maxCLAUDERules = 30

// staleAfterPRs is how far behind the PR watermark a rule's last_seen_pr may
// fall before its rendered source line asks the reader to re-verify it. Keep
// in sync with the "Stale rules" threshold in SKILL.md Step 13.
const staleAfterPRs = 200

// UniversalLocation is the Target.Location sentinel meaning "this rule applies
// to every file in the repo". It is spelled "CLAUDE.md" for backward
// compatibility with existing state.json files written before universal rules
// had a skill of their own; nothing is written to a file by that name.
const UniversalLocation = "CLAUDE.md"

// UniversalSkillName is the domain directory universal rules are generated
// into. They get a real skill like every other rule rather than a repo-root
// file, and it carries no `paths:` gate so it auto-loads everywhere.
const UniversalSkillName = "conventions"

// GeneratedMarker is the first body line of every SKILL.md this package
// writes. It tells readers the file is regenerated from state, and it is how
// Write recognises a skill directory as its own when a domain disappears from
// state (renamed, merged, or every rule rejected): a directory whose SKILL.md
// carries this exact line is pruned, anything else under the skills root is
// left alone. The match is on the whole line, not a substring, so a
// hand-written skill that merely mentions pattern-learner is never touched.
const GeneratedMarker = "<!-- Generated by pattern-learner (write-outputs). Do not edit: this directory is regenerated from .claude/pattern-learner/state.json on every run. -->"

// Options controls optional output features.
type Options struct {
	// RAGHints adds a cursor-agent query hint after each rule in domain skill
	// files so the AI can retrieve live codebase examples at skill-use time.
	RAGHints bool
	// SkillsDir is the explicit destination directory for per-domain skill
	// files. When empty, defaults to <outputDir>/.claude/skills.
	SkillsDir string
	// Owner identifies the repository this run writes for ("owner/repo",
	// lower-case); it is stamped into each generated skill and scopes
	// pruning in a skills directory shared by several repositories. When
	// empty, the state's repo field is used, and when that is empty too the
	// skills are written unstamped.
	Owner string
	// RepoRoot is the root of the repository this run writes for. A skills
	// directory inside it belongs to that repository alone; one outside it
	// is treated as shared. When empty, outputDir is used, which is only
	// safe when outputDir really is the repository root (the CLI resolves
	// the git top level so that a run from an ancestor directory cannot
	// mistake a user-level skills directory for the repo's own).
	RepoRoot string
}

// Write generates the per-domain skill files under opts.SkillsDir (default
// <outputDir>/.claude/skills).
//
// Write deliberately touches nothing above the skills directory. That tree is
// generator-owned and safe to regenerate wholesale; a repo-root instruction
// file (AGENTS.md, CLAUDE.md) is hand-maintained and lives in the user's git
// history, so publishing to it is an explicit, user-initiated step — see
// Promote.
func Write(s state.State, outputDir string, opts Options) error {
	prepared, err := Validate(&s, outputDir, opts)
	if err != nil {
		return err
	}
	return prepared.Write()
}

// isSharedSkillsDir reports whether skillsDir lies outside outputDir (the
// repository being written for). A skills directory inside the repository
// belongs to that repository alone, so a generated skill there carrying
// another repo's stamp can only be the same repository under another
// identity (a fork, a rename, a different remote). One outside it may be
// shared by several repositories, where a different stamp means a
// different repository's skill.
func isSharedSkillsDir(skillsDir, outputDir string) bool {
	absSkills, err1 := resolvePath(skillsDir)
	absOut, err2 := resolvePath(outputDir)
	if err1 != nil || err2 != nil {
		return true
	}
	rel, err := filepath.Rel(absOut, absSkills)
	if err != nil {
		return true
	}
	return IsOutsideRel(rel)
}

// IsInside reports whether path lies within root (symlinks resolved), the
// containment test the CLI uses to decide whether a skills directory is
// the repository's own.
func IsInside(path, root string) bool {
	return !isSharedSkillsDir(path, root)
}

// EscapesRoot reports whether a repository-relative glob or path, once
// cleaned, climbs out of the repository ("../x", ".."). It is the one
// implementation of that test for slash-form globs; the paths gate and the
// anchoring walk both use it so they agree on which globs are in-repo.
func EscapesRoot(glob string) bool {
	c := strings.TrimPrefix(path.Clean(filepath.ToSlash(glob)), "/")
	return c == ".." || strings.HasPrefix(c, "../")
}

// IsOutsideRel reports whether a path returned by filepath.Rel points
// outside the base it was computed from. It is the one implementation of
// that test; a bare HasPrefix(rel, "..") would also match a sibling whose
// name merely starts with two dots.
func IsOutsideRel(rel string) bool {
	return rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// resolvePath returns p as an absolute path with symlinks resolved, so a
// .claude/skills that is a symlink into a user-level directory is judged by
// where it really points. A path that does not exist yet is resolved
// through its nearest existing ancestor.
func resolvePath(p string) (string, error) {
	abs, err := filepath.Abs(p)
	if err != nil {
		return "", err
	}
	var missing []string
	for cur := abs; ; {
		if resolved, err := filepath.EvalSymlinks(cur); err == nil {
			for i := len(missing) - 1; i >= 0; i-- {
				resolved = filepath.Join(resolved, missing[i])
			}
			return resolved, nil
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			return abs, nil
		}
		missing = append(missing, filepath.Base(cur))
		cur = parent
	}
}

// renderUniversalRules writes CLAUDE.md-targeted rules at the given heading level.
func renderUniversalRules(b *strings.Builder, rules []state.Rule, heading string) {
	for _, r := range rules {
		b.WriteString(fmt.Sprintf("%s %s\n\n", heading, r.Title))
		renderExamples(b, r, 1)
		b.WriteString(r.Rule + "\n\n")
		b.WriteString(fmt.Sprintf("_Source: %s_\n\n", sourceLabel(r)))
	}
}

// DedupeStrings returns in without duplicates or empty strings, first
// occurrence order kept.
func DedupeStrings(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if s != "" && !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// Prepared is a run that has passed every pre-write check at the time
// Validate ran. It keeps the state by pointer so the caller can enrich it
// in place between validation and Write (example anchoring adds file
// references); Write checks the state again as it stands at that point.
type Prepared struct {
	state    *state.State
	plan     *plan // the plan that passed validation
	opts     Options
	warnings []string
}

// Validate runs every check a run performs before it touches the skills
// tree (domain names, globs, collisions, and the ownership of whatever is
// already on disk) and returns the first failure, writing nothing. The CLI
// calls it before the expensive example-anchoring step so a run that
// would be refused does not walk the repository first.
func Validate(s *state.State, outputDir string, opts Options) (*Prepared, error) {
	skillsDir, shared := resolveDirs(outputDir, opts)
	p := buildPlan(*s, skillsDir, shared, opts)
	if err := p.validate(); err != nil {
		return nil, err
	}
	return &Prepared{state: s, plan: p, opts: opts}, nil
}

// Write performs the run on the state as it now stands. The checks are
// repeated: the pure ones because the state may have been enriched since
// Validate, the on-disk ones because the anchoring step can take long
// enough for the skills tree to change underneath the run.
func (pr *Prepared) Write() error {
	s := *pr.state
	p := buildPlan(s, pr.plan.skillsDir, pr.plan.shared, pr.opts)
	if err := p.validateRules(); err != nil {
		return err
	}

	// Nothing to write and nothing to prune: leave the tree uncreated.
	if len(p.byDomain) == 0 {
		if _, err := os.Stat(p.skillsDir); err != nil {
			return nil
		}
	}

	// Repair whatever an interrupted earlier run left (a domain mid-swap,
	// a stale staging tree) before judging the tree, so the checks see
	// every domain in its settled place.
	warnings, err := recoverTransients(p.skillsDir, p.owner, !p.shared)
	pr.warnings = warnings // this run's only; a repeated Write reports afresh
	if err != nil {
		return err
	}
	if err := p.validateDisk(); err != nil {
		return err
	}
	pr.warnings = append(pr.warnings, p.warnings...)
	for domain, rules := range p.byDomain {
		if err := writeSkillFile(domain, rules, p.globs[domain], p.isUniversal(domain), p.skillsDir, s.DomainDescriptions[domain], s.LastExtractedPRNumber, p.owner, pr.opts); err != nil {
			return err
		}
	}
	// Prune only once every write has succeeded, so a failed run leaves the
	// previous skills in place rather than a tree with both the old ones
	// removed and the new ones missing. Ownership follows the same rule as
	// the overwrite guard: inside the repo's own tree every generated skill
	// is ours whatever it is stamped with; in a shared directory only those
	// stamped for this run are.
	pruneWarnings, err := pruneStaleSkills(p.skillsDir, p.byDomain, p.owner, !p.shared)
	pr.warnings = append(pr.warnings, pruneWarnings...)
	return err
}

// Warnings reports conditions the run could not resolve on its own and the
// user should hear about (a retired copy left in a shared directory because
// another repository now holds its slot). Available after Write.
func (pr *Prepared) Warnings() []string {
	return pr.warnings
}

// resolveDirs applies the Options defaults for the skills directory and
// decides whether it is shared.
func resolveDirs(outputDir string, opts Options) (skillsDir string, shared bool) {
	// Options.SkillsDir is the explicit destination, used as given; only
	// an empty value takes the default. Resolving a relative value here
	// would apply ResolveSkillsDir a second time to what the CLI already
	// resolved and double the path.
	skillsDir = opts.SkillsDir
	if skillsDir == "" {
		skillsDir = ResolveSkillsDir("", outputDir)
	}
	repoRoot := opts.RepoRoot
	if repoRoot == "" {
		repoRoot = outputDir
	}
	return skillsDir, isSharedSkillsDir(skillsDir, repoRoot)
}

// ResolveSkillsDir is the one place the skills directory is derived from
// its flag: empty means <outputDir>/.claude/skills, a relative value is
// taken against outputDir rather than the process cwd (so the skills, the
// example anchoring and the shared-directory judgement share one base
// wherever the command was run from), and an absolute one is used as is.
func ResolveSkillsDir(flag, outputDir string) string {
	if flag == "" {
		return filepath.Join(outputDir, ".claude", "skills")
	}
	if filepath.IsAbs(flag) {
		return flag
	}
	return filepath.Join(outputDir, flag)
}

// plan is everything a run needs to know before it writes: the approved
// rules grouped by skill domain (universal rules under UniversalSkillName),
// each domain's expanded globs once validated, the owner stamp, and where
// and in what kind of directory the skills go.
type plan struct {
	byDomain  map[string][]state.Rule
	globs     map[string][]string
	owner     string
	skillsDir string
	shared    bool
	// hasUniversal records whether repo-wide rules were merged under
	// UniversalSkillName; only then is that domain rendered ungated.
	hasUniversal bool
	// warnings are conditions validateDisk resolved in the run's favour but
	// the user should hear about; Write hands them to Prepared.
	warnings []string
}

func buildPlan(s state.State, skillsDir string, shared bool, opts Options) *plan {
	byDomain := map[string][]state.Rule{}
	var universal []state.Rule
	for _, r := range s.Rules {
		if r.Status != "approved" || r.Target.Location == "" {
			continue
		}
		if r.Target.Location == UniversalLocation {
			universal = append(universal, r)
			continue
		}
		byDomain[r.Target.Location] = append(byDomain[r.Target.Location], r)
	}

	// Universal rules are a skill too. If a scoped domain happens to already
	// be called "conventions", the two merge into that one skill — and
	// writeSkillFile drops its paths gate, since gating a file that carries
	// repo-wide rules behind a glob would hide them on every other file.
	if len(universal) > 0 {
		byDomain[UniversalSkillName] = append(universal, byDomain[UniversalSkillName]...)
	}

	owner := opts.Owner
	if owner == "" {
		owner = OwnerFromState(s)
	}
	return &plan{byDomain: byDomain, globs: map[string][]string{}, owner: owner, skillsDir: skillsDir, shared: shared, hasUniversal: len(universal) > 0}
}

// isUniversal reports whether domain is rendered as the ungated repo-wide
// skill: the universal domain name, and only when universal rules exist.
func (p *plan) isUniversal(domain string) bool {
	return p.hasUniversal && domain == UniversalSkillName
}

// validate checks every domain before anything is written, so a bad name or
// a collision fails the run with nothing written rather than after a
// map-ordered subset: first the pure checks on the state, then the tree.
func (p *plan) validate() error {
	if err := p.validateRules(); err != nil {
		return err
	}
	return p.validateDisk()
}

// validateRules checks what depends on the state alone (domain names,
// case collisions, globs), sorts each domain's rules into rendering order,
// and records the expanded globs. It touches no files.
func (p *plan) validateRules() error {
	byFold := map[string]string{}
	for domain, rules := range p.byDomain {
		if !validDomain(domain) {
			return fmt.Errorf("skill domain %q is not a valid directory name; re-target its rules to a single-segment domain (e.g. \"api\") and rerun", domain)
		}
		// Two domains differing only by case share one directory on a
		// case-insensitive filesystem, and the second write would wipe the
		// first's examples/ and rules/. Refuse rather than lose rules.
		folded := strings.ToLower(domain)
		if other, dup := byFold[folded]; dup {
			return fmt.Errorf("skill domains %q and %q differ only by case and would share one directory; merge them into a single domain and rerun", other, domain)
		}
		byFold[folded] = domain
		// Sort here, before the globs are collected, so the paths gate and
		// description follow the rendered rule order rather than the order
		// rules happen to sit in state (which the agent rewrites each run).
		sortRules(rules)
		// The universal skill carries no paths gate, so its globs are never
		// emitted and need no validation. A domain that merely shares its
		// name, with no universal rules merged in, is an ordinary scoped
		// skill and keeps its gate.
		if !p.isUniversal(domain) {
			globs, err := collectGlobs(rules)
			if err != nil {
				return fmt.Errorf("skill domain %q: %w", domain, err)
			}
			p.globs[domain] = globs
		}
	}
	return nil
}

// validateDisk checks each domain's slot in the skills tree: nothing that
// this generator did not write is overwritten, symlinked slots are refused,
// and in a shared directory another repository's skill is not clobbered.
// It runs at validation and again just before writing, since the slow
// anchoring step can sit between the two.
func (p *plan) validateDisk() error {
	skillsDir, shared, owner := p.skillsDir, p.shared, p.owner
	// A shared skills directory is kept safe entirely by the owner stamp:
	// it is what stops one repository's run from overwriting another's
	// skill, and what lets a run recognise its own stale skills to prune. A
	// run with no identity has neither, and both consequences used to be
	// silent — it wrote unstamped skills that the next repository with the
	// same domain name could claim, and pruning's unattributable case has
	// no diagnostic of its own, so its stale skills accumulated forever.
	// Writing is still allowed (one repository pointing --skills-dir at a
	// directory of its own is the ordinary case, and nothing is at risk
	// there), but the user is told what the run cannot do for itself.
	if shared && owner == "" && len(p.byDomain) > 0 {
		p.warnings = append(p.warnings, fmt.Sprintf("%s is outside this repository and this run has no repository identity, so its skills are written unstamped: they cannot be told apart from another repository's, which means this run will never prune its own stale skills there and another repository writing the same domain name would take them over. Pass --repo owner/name, set repo in the state file, or add a git remote to have them stamped", skillsDir))
	}
	for domain := range p.byDomain {
		// A directory already at this path that this generator did not
		// write is someone's hand-authored skill (or hand-kept material);
		// overwriting it and wiping its examples/ and rules/ would destroy
		// their work. Inside the repository's own tree, ownership is judged
		// on the generator's fingerprint alone: a generated skill is
		// regeneration whichever repo identity stamped it last (forks and
		// renames change the stamp, not the fact that we wrote it). In a
		// shared skills directory a different stamp is a different
		// repository's skill, and clobbering it would hand that repo our
		// conventions. A directory with no SKILL.md is foreign too, unless
		// it is empty (nothing in it to lose).
		skillDir := filepath.Join(skillsDir, domain)
		var existing skillInfo
		switch classifySlot(skillDir) {
		case slotAbsent, slotDangling, slotEmptyDir:
			// Free (a dangling link is cleared by the swap).
			continue
		case slotSymlinkDir:
			// Regeneration replaces the directory wholesale, which would
			// turn a symlinked domain into a real directory, strand the
			// link target with a stale SKILL.md, and pull the user's files
			// out of it.
			return fmt.Errorf("%s is a symlink; pattern-learner regenerates a domain directory by replacing it, which would break the link — replace it with a real directory, or point --skills-dir at the directory the link targets, then rerun", skillDir)
		case slotFile:
			return fmt.Errorf("%s exists and is a file pattern-learner did not write; refusing to replace it — rename the domain or move the file, then rerun", skillDir)
		case slotDir:
			// A directory with none of the generated entries is what
			// pruning leaves when a user kept files beside a skill that
			// then lost all its rules; regeneration carries those files
			// over, so it is free.
			if !hasGeneratedEntries(skillDir) {
				continue
			}
			// Provenance is read off SKILL.md, so a directory that has the
			// generated companion trees but no SKILL.md cannot be judged
			// either way. It is refused like a foreign one — its examples/
			// and rules/ are entries regeneration replaces, so they are not
			// carried over and would be lost — but it is not *called*
			// foreign: the usual cause is this generator's own run dying
			// between writing the companions and writing SKILL.md, and
			// telling the user we did not write it is simply false.
			if classifySlot(filepath.Join(skillDir, "SKILL.md")) == slotAbsent {
				return fmt.Errorf("%s holds the examples/ and rules/ of a generated skill but no SKILL.md, so it cannot be attributed; if it is the leftover of an interrupted pattern-learner run, delete it and rerun — if the files are yours, move them out of that directory first", skillDir)
			}
			existing = inspectSkill(filepath.Join(skillDir, "SKILL.md"), domain)
			if !existing.generated {
				return fmt.Errorf("%s exists and was not written by pattern-learner; refusing to overwrite it — rename the domain, move that directory, or delete it if it is a leftover from an older pattern-learner build, then rerun", skillDir)
			}
		}
		if shared {
			// A stamp that is not ours marks another repository's skill.
			if existing.stamped && existing.stamp != owner {
				remedy := "rename the domain in one of them or use separate skills directories"
				if p.isUniversal(domain) {
					remedy = "the universal '" + UniversalSkillName + "' skill has a fixed name, so give each repository its own skills directory"
				}
				// A rename, fork, or org transfer changes the stamp without
				// changing who wrote the skill, and neither remedy above
				// applies to it: the two "repositories" are the same one.
				// Repo-local runs are let through for exactly this reason
				// (see the comment above); a shared directory cannot tell
				// the cases apart, so it names the third way out instead of
				// refusing with advice that does not fit.
				runFor := fmt.Sprintf("%q", owner)
				if owner == "" {
					runFor = "an unidentified repository (no --repo, state.repo, or git remote)"
				}
				return fmt.Errorf("%s was generated for repository %q and this run is for %s; the shared skills directory cannot hold both under one domain name — %s, or, if this is that same repository after a rename, fork, or transfer, delete %s (it is regenerated from state) and rerun", skillDir, existing.stamp, runFor, remedy, skillDir)
			}
			// An unstamped generated skill was written by some repository
			// before stamping and cannot be attributed. Regenerating it is
			// the only migration path, and its content is reproducible from
			// whichever state wrote it — but the run doing the regenerating
			// is not necessarily the one that wrote it, so this is a
			// takeover and is reported rather than done silently.
			if existing.generated && !existing.stamped {
				p.warnings = append(p.warnings, fmt.Sprintf("%s is an unstamped generated skill in a shared skills directory, so it cannot be attributed; this run claimed it for %q and stamped it. If another repository wrote it, re-run that repository's write-outputs to get its version back, and give the two repositories separate skills directories", skillDir, owner))
			}
		}
	}
	return nil
}

// OwnerFromState identifies the repository a state file belongs to, so
// generated skills in a skills directory shared by several repositories
// (say a user-level one) are pruned only by the run that owns them. Empty
// when the state carries no repo information. It is the one place the
// state's repo field is turned into a stamp value; the CLI's resolution
// order (flag, then this, then the git remote) calls it too.
func OwnerFromState(s state.State) string {
	return OwnerKey(s.Repo.Owner, s.Repo.Repo)
}

// OwnerKey is the canonical form of a repository identity for stamping:
// "owner/repo", lower-cased. Every path that produces a stamp value goes
// through it so a value written on one run compares equal on the next.
// Empty when either part is missing.
func OwnerKey(owner, repo string) string {
	if owner == "" || repo == "" {
		return ""
	}
	return NormalizeOwnerKey(owner + "/" + repo)
}

// NormalizeOwnerKey turns a user- or model-supplied "owner/repo" (any case,
// optional surrounding slashes) into the canonical stamp value, or "" when
// it is not a usable key: a stray path segment, whitespace, or a newline
// would produce a stamp that never parses back, and an unparseable stamp
// in a shared directory would make the skill unprunable by its own repo.
func NormalizeOwnerKey(s string) string {
	key := strings.ToLower(strings.Trim(s, "/"))
	// A value copied from a clone URL carries ".git"; the repo detection
	// strips it, so the flag path must too or the two never compare equal.
	key = strings.TrimSuffix(key, ".git")
	if !ValidOwnerKey(key) {
		return ""
	}
	return key
}

// ValidOwnerKey reports whether s is a value OwnerKey could have produced:
// exactly one "/", no whitespace, both halves non-empty.
func ValidOwnerKey(s string) bool {
	parts := strings.Split(s, "/")
	return len(parts) == 2 && parts[0] != "" && parts[1] != "" && strings.Join(strings.Fields(s), "") == s
}

// The owner stamp written under GeneratedMarker. Writing and parsing both
// go through these two constants so the format cannot drift between them.
const (
	ownerStampPrefix = "<!-- pattern-learner:repo="
	ownerStampSuffix = " -->"
)

func ownerLine(owner string) string {
	return ownerStampPrefix + owner + ownerStampSuffix
}

// parseOwnerLine returns the owner named by a stamp line, and whether line
// is a stamp at all.
func parseOwnerLine(line string) (string, bool) {
	if !strings.HasPrefix(line, ownerStampPrefix) || !strings.HasSuffix(line, ownerStampSuffix) {
		return "", false
	}
	return strings.TrimSuffix(strings.TrimPrefix(line, ownerStampPrefix), ownerStampSuffix), true
}

// slotKind is what occupies a domain's path in the skills directory. Every
// place that has to decide what to do with that path (the overwrite guard,
// interrupted-swap recovery, the swap itself) classifies it through
// classifySlot, so their policies cannot drift apart.
type slotKind int

const (
	slotAbsent     slotKind = iota // nothing there
	slotDangling                   // a symlink to nothing
	slotFile                       // a regular file (or other non-directory)
	slotSymlinkDir                 // a symlink resolving to a directory
	slotEmptyDir                   // a directory with nothing to lose
	slotDir                        // a real directory with contents
)

func classifySlot(path string) slotKind {
	lst, lstErr := os.Lstat(path)
	if lstErr != nil {
		return slotAbsent
	}
	fi, statErr := os.Stat(path)
	switch {
	case statErr != nil && os.IsNotExist(statErr):
		return slotDangling
	case statErr != nil:
		// Lstat saw an entry that Stat cannot follow (a link into a
		// directory this user cannot read, a link loop): not free, and not
		// something to delete to make room, so it is judged as a link.
		return slotSymlinkDir
	case !fi.IsDir():
		return slotFile
	case lst.Mode()&os.ModeSymlink != 0:
		return slotSymlinkDir
	case isEmptyDir(path):
		return slotEmptyDir
	}
	return slotDir
}

// isEmptyDir reports whether dir exists and holds nothing to lose: no
// entries, or only the SKILL.md temp file an older build's interrupted
// atomicWrite left behind (before domains were staged and swapped whole).
func isEmptyDir(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	leftover := filepath.Base(tmpPath("SKILL.md"))
	for _, e := range entries {
		if e.Name() != leftover {
			return false
		}
	}
	return true
}

// Each domain is written into a staging sibling and swapped into place, so
// a domain directory is only ever seen complete or absent. These markers
// name the two transient siblings ("<domain><marker>-<random>"); anything
// carrying one was written by this generator and is settled by the next
// run that owns it. The random tail keeps one run's transients from
// colliding with another's, so a leftover another repository left in a
// shared directory can never block this repository's swap.
const (
	stagingSuffix = ".pattern-learner-staging"
	retiredSuffix = ".pattern-learner-old"
)

// reTransient matches exactly the names transientPath produces: the marker
// and an 8-hex-digit tail must end the name, so a user's
// "README.pattern-learner-old.md", "api.pattern-learner-old-backup", or a
// hand-made "api.pattern-learner-old" copy is never taken for one of ours.
var reTransient = regexp.MustCompile(`^(.+)(` + regexp.QuoteMeta(stagingSuffix) + `|` + regexp.QuoteMeta(retiredSuffix) + `)-[0-9a-f]{8}$`)

func isTransientDir(name string) bool {
	return reTransient.MatchString(name)
}

// abandonedAfter is how long a staging tree with no SKILL.md may exist
// before it is taken for the leftover of a dead run rather than another
// run's render in progress. Rendering a domain takes well under this.
//
// This age check is all the concurrency defence the generator has, and it
// is deliberately all it has. An exclusive lock file lived here briefly and
// was removed: a run whose own lock had been broken as stale went on to
// delete its successor's lock, so the mutual exclusion failed in exactly
// the case it existed for. The pipeline is driven interactively by an agent
// following a skill document, so two runs sharing one skills directory is
// rare; when it does happen, this check keeps a render in progress from
// being cleared, and a domain swap is a rename either way.
var abandonedAfter = 10 * time.Minute

// transientPath returns a fresh sibling name for base with the given marker.
func transientPath(base, marker string) string {
	var b [4]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}
	return base + marker + "-" + hex.EncodeToString(b[:])
}

// transientExtraBytes is how much longer than its domain the longest
// transient sibling name is; validDomain leaves this much room under the
// file-name limit so the sibling can always be created.
var transientExtraBytes = len(transientPath("", stagingSuffix))

// liveOfRetired returns the live directory name a retired sibling belongs
// to, and whether name is a retired sibling at all.
func liveOfRetired(name string) (string, bool) {
	m := reTransient.FindStringSubmatch(name)
	if m == nil || m[2] != retiredSuffix {
		return "", false
	}
	return m[1], true
}

// recoverTransients settles whatever an interrupted swap left under
// skillsDir. A retired copy whose live directory is absent is the only copy
// (the run died between swapDir's two renames) and is put back; one beside
// a live directory is the previous version, whose user-added files are
// carried over before it is removed; a staging tree is an unfinished render
// and is removed. In a shared directory a transient is only touched when it
// is ours to touch: stamped for this owner, unstamped, or without a
// SKILL.md at all (too incomplete to belong to anyone).
func recoverTransients(skillsDir, owner string, anyOwner bool) (warnings []string, err error) {
	entries, err := os.ReadDir(skillsDir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		name := e.Name()
		if !isTransientDir(name) {
			continue
		}
		dir := filepath.Join(skillsDir, name)
		// A transient that is not a real directory (a dangling symlink that
		// got retired, a stray file) holds nothing to restore or carry.
		if fi, err := os.Stat(dir); err != nil || !fi.IsDir() {
			if err := os.RemoveAll(dir); err != nil {
				return warnings, err
			}
			continue
		}
		info := inspectSkill(filepath.Join(dir, "SKILL.md"), "")
		if !anyOwner && info.stamped && info.stamp != owner {
			continue
		}
		liveName, retired := liveOfRetired(name)
		// A staging tree with no SKILL.md yet may be another run's render
		// in progress (SKILL.md is the first file written, so the window is
		// brief); only one that has sat untouched for a while is abandoned.
		// A retired copy can never be a render in progress: it is judged
		// on what it holds, whatever its age.
		if !retired && !info.generated && !info.stamped {
			if fi, err := os.Stat(dir); err == nil && time.Since(fi.ModTime()) < abandonedAfter {
				continue
			}
		}
		if retired {
			live := filepath.Join(skillsDir, liveName)
			leftover := func(why string) {
				warnings = append(warnings, fmt.Sprintf("%s holds this repository's previous %q skill (and any files kept beside it) from an interrupted run, but %s %s; move anything you want out of the leftover and delete it", dir, liveName, live, why))
			}
			switch classifySlot(live) {
			case slotAbsent, slotDangling, slotEmptyDir:
				// Free (a dangling link or an empty directory gives way,
				// as the overwrite guard allows): the retired copy goes
				// back wholesale.
				if err := os.RemoveAll(live); err != nil {
					return warnings, err
				}
				if err := os.Rename(dir, live); err != nil {
					return warnings, err
				}
				continue
			case slotFile:
				// A stray file is the user's and is left alone, like the
				// overwrite guard leaves it.
				leftover("is now a file that pattern-learner did not write")
				continue
			case slotSymlinkDir:
				// A resolving symlink is refused by validateDisk when the
				// domain is live; folding our files through it first would
				// move them into the link target before that refusal.
				leftover("is now a symlink")
				continue
			}
			// The live slot is taken. Our retired copy is folded into it
			// only when what is there is a generated skill this run may
			// regenerate anyway, by the same rule validateDisk applies:
			// inside the repo's tree any generated skill, in a shared
			// directory one stamped for us or not stamped at all. Anything
			// else (a hand-written skill, another repository's) must not
			// receive our files, so the copy is left and the user told.
			liveInfo := inspectSkill(filepath.Join(live, "SKILL.md"), liveName)
			ours := !hasGeneratedEntries(live) || (liveInfo.generated && (anyOwner || !liveInfo.stamped || liveInfo.stamp == owner))
			if !ours {
				if liveInfo.generated {
					leftover(fmt.Sprintf("now belongs to repository %q", liveInfo.stamp))
				} else {
					leftover("was not written by pattern-learner")
				}
				continue
			}
			kept, err := carryOver(dir, live)
			if err != nil {
				return warnings, err
			}
			if len(kept) > 0 {
				// Same-named entries already in the live directory win;
				// the older copies must not vanish unannounced.
				leftover(fmt.Sprintf("already holds %s, so the older copies in the leftover were not moved", strings.Join(kept, ", ")))
				continue
			}
		}
		if err := os.RemoveAll(dir); err != nil {
			return warnings, err
		}
	}
	return warnings, nil
}

// generatedEntries are the top-level names a rendered skill directory
// contains. Anything else found in a previous version of the directory is
// the user's and is carried over when the directory is regenerated.
var generatedEntries = map[string]bool{"SKILL.md": true, "examples": true, "rules": true}

// hasGeneratedEntries reports whether dir holds any entry the generator
// writes (SKILL.md, examples/, rules/).
func hasGeneratedEntries(dir string) bool {
	for name := range generatedEntries {
		if _, err := os.Lstat(filepath.Join(dir, name)); err == nil {
			return true
		}
	}
	return false
}

// carryOver moves every entry of from that the generator does not write
// into to, so files a user keeps beside a generated SKILL.md survive
// regeneration. An entry to already has is left as it is and reported in
// kept, so the caller can tell the user before discarding from.
func carryOver(from, to string) (kept []string, err error) {
	entries, err := os.ReadDir(from)
	if err != nil {
		return nil, err
	}
	leftoverTmp := filepath.Base(tmpPath("SKILL.md"))
	for _, e := range entries {
		// The generator's own entries are replaced, and the temp file of
		// an older build's interrupted write is debris, not the user's.
		if generatedEntries[e.Name()] || e.Name() == leftoverTmp {
			continue
		}
		dst := filepath.Join(to, e.Name())
		if _, err := os.Lstat(dst); err == nil {
			kept = append(kept, e.Name())
			continue
		}
		if err := os.Rename(filepath.Join(from, e.Name()), dst); err != nil {
			return kept, err
		}
	}
	return kept, nil
}

// pruneStaleSkills removes generated skill directories under skillsDir whose
// domain no longer has approved rules. Without this, a renamed or merged
// domain (or one whose rules were all rejected) leaves its old SKILL.md
// behind, and the consuming agent keeps auto-loading conventions that state
// no longer holds. Only directories whose SKILL.md this generator wrote for
// this repository (see inspectSkill) are candidates; hand-authored
// skills and other repositories' generated skills sharing the root are
// never removed.
//
// With anyOwner set (the repo's own tree) every generated skill stamped for
// this owner or not stamped at all is ours. One stamped for a different
// repository is ambiguous even there: a fork or rename leaves stale skills
// under the old identity, but a user may also have copied another
// repository's generated skill in to reuse it. Deleting the latter is
// worse than leaving the former, so such a skill is left in place and
// reported (a live domain still regenerates and re-stamps it). In a shared
// directory only a skill stamped for this owner is ours: an unstamped one
// was written before stamping by some repository that cannot be identified.
//
// An entry is live when it exactly names a live domain. It is also treated
// as live when it names one case-insensitively and the exact-cased directory
// is absent: on a case-insensitive filesystem that is the very directory
// just written, showing under its older casing. When both casings exist as
// separate entries (a case-sensitive filesystem after a re-cased domain),
// the non-matching one is a stale skill and is pruned like any other.
func pruneStaleSkills(skillsDir string, live map[string][]state.Rule, owner string, anyOwner bool) (warnings []string, err error) {
	entries, err := os.ReadDir(skillsDir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	present := map[string]bool{}
	for _, e := range entries {
		present[e.Name()] = true
	}
	for _, e := range entries {
		dir := filepath.Join(skillsDir, e.Name())
		// Transients were settled by recoverTransients before any write;
		// one still here belongs to another repository.
		if isTransientDir(e.Name()) {
			continue
		}
		// A symlinked skill is judged by its target (so a stale one stops
		// auto-loading) but only the link is ever removed: the target may
		// be another repository's skill or a user's own directory.
		isLink := false
		if lst, err := os.Lstat(dir); err == nil && lst.Mode()&os.ModeSymlink != 0 {
			isLink = true
		}
		if st, err := os.Stat(dir); err != nil || !st.IsDir() {
			continue
		}
		if _, ok := live[e.Name()]; ok {
			continue
		}
		aliasOfLive := false
		for domain := range live {
			if strings.EqualFold(domain, e.Name()) && !present[domain] {
				aliasOfLive = true
				break
			}
		}
		if aliasOfLive {
			continue
		}
		info := inspectSkill(filepath.Join(dir, "SKILL.md"), e.Name())
		if !info.generated {
			continue
		}
		if !anyOwner && (!info.stamped || info.stamp != owner) {
			continue
		}
		// A run with no identity of its own cannot tell a foreign stamp
		// from its former one; inside its own tree it owns every generated
		// skill, as the overwrite guard already holds.
		if anyOwner && owner != "" && info.stamped && info.stamp != owner {
			warnings = append(warnings, fmt.Sprintf("%s is a generated skill stamped for repository %q with no approved rules in this state; it was left in place because it may have been copied in on purpose — delete it if it is a leftover from before this repository was forked or renamed", dir, info.stamp))
			continue
		}
		if isLink {
			if err := os.Remove(dir); err != nil {
				return warnings, err
			}
			continue
		}
		if err := removeGenerated(dir); err != nil {
			return warnings, err
		}
	}
	return warnings, nil
}

// removeGenerated removes what the generator wrote in a stale skill
// directory (SKILL.md, examples/, rules/) and then the directory itself if
// nothing else is in it. Files a user kept beside the generated ones are
// left where they are, under the same carry-over guarantee regeneration
// gives them; without a SKILL.md the directory is no longer a skill and
// nothing auto-loads from it.
func removeGenerated(dir string) error {
	for name := range generatedEntries {
		if err := os.RemoveAll(filepath.Join(dir, name)); err != nil {
			return err
		}
	}
	if isEmptyDir(dir) {
		return os.RemoveAll(dir)
	}
	return nil
}

// The fixed explanatory sentences the generator writes into a skill body.
// Besides being rendered, they double as fingerprints (generatedBodyLines)
// for skills written by builds that predate GeneratedMarker. If one is ever
// reworded, keep the old wording in generatedBodyLines as well: files
// carrying it are still out there.
const (
	inlineRulesIntro    = "Rules with examples link a file under `examples/` — read it at your discretion for do/don't code and real instances before writing code the rule covers."
	chunkedIndexIntro   = "This skill is chunked to keep SKILL.md small: each rule lives in its own file under `rules/`, examples included. Find matching rules in the index below (by title or glob) and read only those files. For a full-text lookup, grep the `rules/` directory next to this file, e.g. `grep -ril \"<keyword>\" rules/`."
	exemplaryFilesIntro = "Read one of these before writing new code in this domain — they best represent the team's style:"
)

// generatedBodyLines are whole lines that identify a skill written by a
// build that predates GeneratedMarker (the first two since the
// progressive-disclosure layout, the third for longer), which is the
// population pruning was added to clean up. Each is long and exact, so a
// hand-written skill cannot match by accident. A skill from a build older
// than all three carries no fingerprint and must be removed by hand;
// SKILL.md says so.
var generatedBodyLines = []string{inlineRulesIntro, chunkedIndexIntro, exemplaryFilesIntro}

// skillInfo is what one read of a SKILL.md tells us about its provenance.
type skillInfo struct {
	// generated: the file carries the generator's fingerprint and its
	// frontmatter name matches its directory.
	generated bool
	// stamp is the repository named by the owner stamp line, when stamped.
	stamp   string
	stamped bool
}

// inspectSkill reads the SKILL.md at path once and reports whether this
// package wrote it for the skill directory dirName, and for which
// repository. It is generated when both hold:
//
//   - the frontmatter name equals dirName (ignoring case, since on a
//     case-insensitive filesystem the path may resolve through an older
//     casing of the directory), so a generated skill a user copied elsewhere
//     and adopted ("api-style/" carrying name "api") is not mistaken for the
//     generator's own output; and
//   - the body carries GeneratedMarker or, for a file from a build that
//     predates the marker, one of generatedBodyLines as a whole line.
//
// A generated skill kept under its original directory name and hand-edited
// is still recognised: that directory is documented as generator-owned and
// regenerated wholesale, so its edits were never safe. Whether a generated
// skill is *ours* is the caller's decision, made from the stamp.
func inspectSkill(path, dirName string) skillInfo {
	data, err := os.ReadFile(path)
	if err != nil {
		return skillInfo{}
	}
	content := string(data)
	var info skillInfo
	// One pass through the module's frontmatter reader gives both the name
	// and the body. A block that is not valid YAML (every skill this
	// generator wrote before it quoted its frontmatter) still yields the
	// name via the reader's line-by-line fallback, so those skills are
	// recognised. With dirName empty the name is not checked, for callers
	// that only need the stamp.
	fields, body, _ := format.ParseFrontmatter(content)
	name := fields["name"]
	nameMatches := dirName == "" || (name != "" && strings.EqualFold(name, dirName))

	// Only the header region is inspected, where the generator puts these
	// lines: the marker and stamp are the first body lines after the
	// frontmatter, and the fixed sentences precede the first rule heading
	// or index entry. A hand-written skill that quotes one of them further
	// down (say, in a rule about pattern-learner itself) must not be taken
	// for generated output.
	fingerprinted := false
	nonEmpty := 0
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		nonEmpty++
		if strings.HasPrefix(line, "### ") || strings.HasPrefix(line, "- [") {
			break
		}
		if nonEmpty <= headerLineBudget {
			if stamped, ok := parseOwnerLine(line); ok && !info.stamped {
				info.stamp, info.stamped = stamped, true
			}
			if line == GeneratedMarker {
				fingerprinted = true
				continue
			}
		}
		for _, generated := range generatedBodyLines {
			if line == generated {
				fingerprinted = true
			}
		}
	}
	info.generated = nameMatches && fingerprinted
	return info
}

// headerLineBudget is how many non-empty body lines from the top the marker
// and owner stamp may occupy. The generator writes them first and second.
const headerLineBudget = 2

// sortRules orders rules for rendering: stated, then established, then
// emerging, alphabetically by title within each tier.
func sortRules(rules []state.Rule) {
	sort.Slice(rules, func(i, j int) bool {
		ri, rj := confidenceRank(rules[i].Confidence), confidenceRank(rules[j].Confidence)
		if ri != rj {
			return ri < rj
		}
		return rules[i].Title < rules[j].Title
	})
}

// writeSkillFile renders one domain; rules must already be in rendering
// order (plan.validate sorts them before collecting globs).
func writeSkillFile(domain string, rules []state.Rule, globs []string, universal bool, skillsDir string, override string, watermark int, owner string, opts Options) error {
	// globs is nil for the universal skill: validateRules records none for
	// it, so it auto-loads regardless of what is being edited.
	desc := buildDescription(domain, globs, universal, override)
	skillDir := filepath.Join(skillsDir, domain)

	// The whole domain is rendered into a staging sibling and then swapped
	// into place, so the live directory is only ever complete or absent: an
	// interrupted run leaves the previous skill untouched (plus a transient
	// sibling the next run clears), never a SKILL.md pointing at companion
	// files that were wiped and not rewritten. Rendering from scratch also
	// means renamed or removed rules leave no stale companion files behind.
	staging := transientPath(skillDir, stagingSuffix)
	retired := transientPath(skillDir, retiredSuffix)
	if err := renderSkillDir(staging, domain, desc, globs, universal, rules, watermark, owner, opts); err != nil {
		os.RemoveAll(staging)
		return err
	}
	if err := swapDir(staging, skillDir, retired); err != nil {
		os.RemoveAll(staging)
		return err
	}
	return nil
}

// renderSkillDir writes a domain's complete skill tree (SKILL.md plus
// companion files) under dir.
func renderSkillDir(dir, domain, desc string, globs []string, universal bool, rules []state.Rule, watermark int, owner string, opts Options) error {
	slugs := ruleSlugs(rules)
	header := renderSkillHeader(domain, desc, globs, universal, rules, owner)

	// Examples always live in companion files (progressive disclosure): the
	// SKILL.md body is a recurring token cost once loaded, so it carries only
	// the imperative rules plus pointers the consuming agent follows at its
	// discretion when it wants the do/don't code.
	inline := header + renderInlineRules(rules, slugs, watermark, opts)
	if bodyLines(inline) < maxSkillBodyLines {
		if err := atomicWrite(filepath.Join(dir, "SKILL.md"), inline); err != nil {
			return err
		}
		return writeExampleFiles(dir, rules, slugs)
	}

	// Very large skill: chunk per the Claude Code guidance ("Keep SKILL.md
	// under 500 lines. Move detailed reference material to separate files.").
	// SKILL.md becomes a rule index; each rule lives in rules/<slug>.md with
	// its examples inline (the chunk itself is loaded on demand), and the
	// chunk corpus doubles as a grep target for full-text lookup.
	if err := atomicWrite(filepath.Join(dir, "SKILL.md"), header+renderRuleIndex(rules, slugs)); err != nil {
		return err
	}
	return writeRuleChunks(dir, rules, slugs, watermark, opts)
}

// swapDir moves the complete tree at staging to live, retiring whatever was
// at live first. If the final rename fails the previous tree is put back,
// so live is never left absent when it existed before. Files the user kept
// in the previous tree beside the generated ones are carried over into the
// new one before the previous tree is removed.
func swapDir(staging, live, retired string) error {
	hadLive := false
	switch classifySlot(live) {
	case slotDir, slotEmptyDir:
		hadLive = true
		if err := os.Rename(live, retired); err != nil {
			return err
		}
	case slotDangling:
		// Nothing to retire, but the dead link must not block the rename.
		if err := os.RemoveAll(live); err != nil {
			return err
		}
	case slotFile, slotSymlinkDir:
		// validateDisk refused these; one appearing since (the anchoring
		// window) is the user's and is not deleted to make room.
		return fmt.Errorf("%s appeared since validation and was not written by pattern-learner; rerun", live)
	}
	if err := os.Rename(staging, live); err != nil {
		if hadLive {
			os.Rename(retired, live)
		}
		return err
	}
	if hadLive {
		// A freshly rendered tree holds only generated entries, so nothing
		// a user kept can collide and be left behind here.
		if _, err := carryOver(retired, live); err != nil {
			return err
		}
		return os.RemoveAll(retired)
	}
	return nil
}

// maxSkillBodyLines is the chunking threshold for a generated domain
// SKILL.md, with headroom under the documented limit ("Keep SKILL.md under
// 500 lines").
//
// It is the audit's *warn* threshold, and it is counted the way the audit
// counts — body lines only, frontmatter excluded — because the two have to
// agree. They did not: chunking triggered above 450 lines of whole file
// while audit-format warns at 400 lines of body, so a domain landing in the
// band between rendered inline and then came back `approaching_budget`,
// which Step 12.5 of the learn-patterns skill tells the agent is a
// generator bug to stop the run and report. Chunking at the same number the
// audit warns at closes the band: a skill this generator emits can never
// report approaching_budget or over_budget.
const maxSkillBodyLines = format.BodyLineWarn

// bodyLines counts a rendered SKILL.md the way audit-format will: the
// frontmatter block is parsed off and only what follows is counted.
func bodyLines(skill string) int {
	_, body, _ := format.ParseFrontmatter(skill)
	return countBodyLines(body)
}

// countBodyLines mirrors format.countLines (a trailing newline does not add
// an empty final line), so the generator's own budget check and the audit
// that later grades its output never disagree by one.
func countBodyLines(body string) int {
	if body == "" {
		return 0
	}
	n := strings.Count(body, "\n")
	if strings.HasSuffix(body, "\n") {
		return n
	}
	return n + 1
}

// maxExamplePairs caps rendered do/don't pairs; state caps the arrays at 4.
const maxExamplePairs = 4

func renderSkillHeader(domain, desc string, globs []string, universal bool, rules []state.Rule, owner string) string {
	var b strings.Builder
	// Every value is emitted as a double-quoted YAML scalar. Claude Code
	// parses this block as real YAML, and unquoted values break in exactly
	// the shapes this generator produces: a description containing ": "
	// ("Conventions for HTTP API endpoints: error responses, ...") is a
	// mapping-value error, and a glob starting with "*" ("*.tsx", "**/*.go")
	// is read as an alias. Either makes the whole skill fail to load.
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("name: %s\n", yamlQuote(domain)))
	b.WriteString(fmt.Sprintf("description: %s\n", yamlQuote(desc)))
	// paths gates auto-loading to work on matching files, so chain-loading
	// several domain skills only ever pulls in the ones actually in play.
	// The documented form is one quoted comma-separated string.
	if len(globs) > 0 {
		b.WriteString(fmt.Sprintf("paths: %s\n", yamlQuote(strings.Join(globs, ","))))
	}
	b.WriteString("---\n\n")
	b.WriteString(GeneratedMarker + "\n")
	if owner != "" {
		b.WriteString(ownerLine(owner) + "\n")
	}
	b.WriteString("\n")
	// "conventions" is already the noun, so don't render "Conventions Conventions".
	switch {
	case universal:
		b.WriteString("# Repo-Wide Conventions\n\n")
		// The blanket sentence is only true when every rule here is
		// repo-wide. It is not when a scoped domain happened to be named
		// UniversalSkillName and got merged in by buildPlan: those rules keep
		// their own file_glob, which this file carries no paths gate for.
		// Claiming they govern every file would contradict the state they
		// came from, so say what is actually true and point at the per-rule
		// scope lines renderInlineRules emits for exactly this case.
		if uniformScope(rules) {
			b.WriteString("These rules apply to every file in this repository, regardless of what you are editing.\n\n")
		} else {
			b.WriteString("These rules apply to every file in this repository, regardless of what you are editing — except where a rule names an **Applies to:** scope of its own, which narrows it to the files that scope matches.\n\n")
		}
	case strings.EqualFold(headingTitle(domain), "Conventions"):
		b.WriteString("# Conventions\n\n")
	default:
		b.WriteString(fmt.Sprintf("# %s Conventions\n\n", headingTitle(domain)))
	}

	if exemplary := exemplaryFiles(rules); len(exemplary) > 0 {
		b.WriteString("## Exemplary Files\n\n")
		b.WriteString(exemplaryFilesIntro + "\n\n")
		for _, f := range exemplary {
			b.WriteString(fmt.Sprintf("- `%s`\n", f))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderInlineRules(rules []state.Rule, slugs []string, watermark int, opts Options) string {
	var b strings.Builder
	b.WriteString("## Rules\n\n")
	b.WriteString(inlineRulesIntro + "\n\n")
	// The paths gate is the union of every rule's globs, so a skill loaded
	// for one file carries rules scoped to others. When the rules do not all
	// share one scope, each states its own — the chunked layout has always
	// done this ("Applies to:" in writeRuleChunks) and the inline layout
	// dropped it, so the same rule read narrowly in one layout read
	// repo-wide in the other. When every rule shares one scope the frontmatter
	// already says it and per-rule lines would only cost body budget.
	perRuleScope := !uniformScope(rules)
	for i, r := range rules {
		b.WriteString(fmt.Sprintf("### %s\n\n", r.Title))
		if perRuleScope {
			b.WriteString(scopeLine(r) + "\n\n")
		}
		b.WriteString(r.Rule + "\n\n")
		if hasExamples(r) {
			b.WriteString(fmt.Sprintf("_Examples: `examples/%s.md`_\n\n", slugs[i]))
		}
		writeSourceLine(&b, r, watermark)
		writeRAGHint(&b, r, opts)
	}
	return b.String()
}

// uniformScope reports whether every rule in a domain is scoped to the same
// set of globs, which is when the frontmatter `paths` gate describes each
// rule as accurately as a per-rule line would.
func uniformScope(rules []state.Rule) bool {
	if len(rules) < 2 {
		return true
	}
	first := scopeKey(rules[0])
	for _, r := range rules[1:] {
		if scopeKey(r) != first {
			return false
		}
	}
	return true
}

func scopeKey(r state.Rule) string {
	return strings.Join(DedupeStrings(r.Target.FileGlob), "\x00")
}

// scopeLine states one rule's own scope in the body. A rule with no globs
// is a repo-wide rule; saying so matters most in the merged domain, where
// it sits beside scoped ones under a heading that speaks for the whole file.
func scopeLine(r state.Rule) string {
	globs := DedupeStrings(r.Target.FileGlob)
	if len(globs) == 0 {
		return "**Applies to:** every file in this repository."
	}
	return "**Applies to:** `" + strings.Join(globs, "`, `") + "`"
}

// writeExampleFiles writes one examples/<slug>.md per rule that has examples,
// holding every do/don't pair plus real-instance refs.
func writeExampleFiles(skillDir string, rules []state.Rule, slugs []string) error {
	for i, r := range rules {
		if !hasExamples(r) {
			continue
		}
		var b strings.Builder
		b.WriteString(fmt.Sprintf("# Examples — %s\n\n", r.Title))
		b.WriteString(r.Rule + "\n\n")
		renderExamples(&b, r, maxExamplePairs)
		if err := atomicWrite(filepath.Join(skillDir, "examples", slugs[i]+".md"), b.String()); err != nil {
			return err
		}
	}
	return nil
}

// writeRuleChunks writes one rules/<slug>.md per rule for the chunked layout.
func writeRuleChunks(skillDir string, rules []state.Rule, slugs []string, watermark int, opts Options) error {
	for i, r := range rules {
		var b strings.Builder
		b.WriteString(fmt.Sprintf("# %s\n\n", r.Title))
		meta := fmt.Sprintf("**Confidence:** %s", r.Confidence)
		if len(r.Target.FileGlob) > 0 {
			meta += " · **Applies to:** `" + strings.Join(r.Target.FileGlob, "`, `") + "`"
		}
		b.WriteString(meta + "\n\n")
		renderExamples(&b, r, maxExamplePairs)
		b.WriteString(r.Rule + "\n\n")
		writeSourceLine(&b, r, watermark)
		writeRAGHint(&b, r, opts)
		if err := atomicWrite(filepath.Join(skillDir, "rules", slugs[i]+".md"), b.String()); err != nil {
			return err
		}
	}
	return nil
}

func renderRuleIndex(rules []state.Rule, slugs []string) string {
	var b strings.Builder
	b.WriteString(chunkedIndexIntro + "\n\n")
	b.WriteString("## Rule Index\n\n")
	last := ""
	for i, r := range rules {
		if r.Confidence != last {
			b.WriteString(fmt.Sprintf("### %s\n\n", confidenceHeading(r.Confidence)))
			last = r.Confidence
		}
		line := fmt.Sprintf("- [%s](rules/%s.md)", r.Title, slugs[i])
		if len(r.Target.FileGlob) > 0 {
			line += " — `" + strings.Join(r.Target.FileGlob, "`, `") + "`"
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n")
	return b.String()
}

func confidenceHeading(c string) string {
	switch c {
	case "stated":
		return "Stated (explicit preferences)"
	case "established":
		return "Established"
	case "emerging":
		return "Emerging"
	default:
		return capitalize(c)
	}
}

func writeSourceLine(b *strings.Builder, r state.Rule, watermark int) {
	// A rule a watched reviewer has flagged since is not stale, whatever its
	// last PR number says — the same judgement classify makes when it exempts
	// such a rule from the recency downgrade. Telling the reader to re-verify
	// a convention two fresh reviews just confirmed would contradict it.
	prOrigin := (r.Origin == "" || r.Origin == "pr-review") && !hasReviewSource(r.Sources)
	if prOrigin && watermark > 0 && r.LastSeenPR > 0 && watermark-r.LastSeenPR >= staleAfterPRs {
		b.WriteString(fmt.Sprintf("_Source: %s_ _(last seen: PR #%d — verify this convention is still current)_\n\n",
			sourceLabel(r), r.LastSeenPR))
		return
	}
	b.WriteString(fmt.Sprintf("_Source: %s_\n\n", sourceLabel(r)))
}

// ragHintTitle prepares a rule title for the RAG hint, which is a shell
// command inside a markdown code span that the agent may paste verbatim.
// Quotes, backslashes and dollars are escaped for the shell; backticks are
// dropped because a code span cannot contain one (backslash escapes do not
// apply inside spans), and the title reads fine without them.
var ragHintTitle = strings.NewReplacer(`\`, `\\`, `"`, `\"`, "$", `\$`, "`", "")

func writeRAGHint(b *strings.Builder, r state.Rule, opts Options) {
	if !opts.RAGHints {
		return
	}
	b.WriteString(fmt.Sprintf(
		"_Live examples: `cursor-agent -p --mode=ask \"Show me 3 real examples of '%s' in this codebase with file paths\"`_\n\n",
		ragHintTitle.Replace(r.Title),
	))
}

func hasExamples(r state.Rule) bool {
	return len(effectiveDoExamples(r)) > 0 || len(effectiveDontExamples(r)) > 0
}

// slugify converts a rule title to a filesystem-safe slug.
func slugify(title string) string {
	var out []rune
	lastDash := true // also trims leading dashes
	for _, r := range strings.ToLower(title) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			out = append(out, r)
			lastDash = false
		} else if !lastDash {
			out = append(out, '-')
			lastDash = true
		}
	}
	s := strings.Trim(string(out), "-")
	if len(s) > 60 {
		s = strings.Trim(s[:60], "-")
	}
	if s == "" {
		return "rule"
	}
	return s
}

// ruleSlugs returns one unique slug per rule (suffixing -2, -3, … on collision).
func ruleSlugs(rules []state.Rule) []string {
	// Every name handed out is recorded, the suffixed ones included, and a
	// candidate is retried until it is free. Counting only the bare slugs
	// is not enough: two rules titled "Use Tabs" produce "use-tabs" and
	// "use-tabs-2", and a third titled "Use Tabs 2" slugifies to
	// "use-tabs-2" on its own — a name the counter has never seen. The two
	// then share a companion file, so in the inline layout one rule's
	// examples/<slug>.md silently overwrites the other's, and in the
	// chunked layout one approved rule is missing from the tree entirely
	// while the index still links to its slug.
	seen := map[string]bool{}
	out := make([]string, len(rules))
	for i, r := range rules {
		base := slugify(r.Title)
		s := base
		for n := 2; seen[s]; n++ {
			s = fmt.Sprintf("%s-%d", base, n)
		}
		seen[s] = true
		out[i] = s
	}
	return out
}

// renderExamples writes do/don't example pairs (up to maxPairs) before rule prose.
// Prefers DoExamples/DontExamples (plural); falls back to DoExample/DontExample for
// rules created before plural support was added.
func renderExamples(b *strings.Builder, r state.Rule, maxPairs int) {
	dos := effectiveDoExamples(r)
	donts := effectiveDontExamples(r)

	if len(dos) == 0 && len(donts) == 0 {
		return
	}

	n := len(dos)
	if len(donts) > n {
		n = len(donts)
	}
	if n > maxPairs {
		n = maxPairs
	}

	for i := 0; i < n; i++ {
		if i < len(dos) {
			b.WriteString("**Do:**\n" + fencedCode(dos[i]))
			if dos[i].FileRef != "" {
				b.WriteString(fmt.Sprintf("_Real instance: see %s_\n", dos[i].FileRef))
			}
			b.WriteString("\n")
		}
		if i < len(donts) {
			b.WriteString("**Don't:**\n" + fencedCode(donts[i]) + "\n")
		}
	}
}

// fencedCode renders one example as a markdown code block. The fence is
// always longer than the longest backtick run in the code, so an example
// that itself contains a fence (a reviewer quoting a suggestion block, say)
// cannot close the block early and turn the rest of the snippet into prose.
func fencedCode(ex state.Example) string {
	fence := strings.Repeat("`", maxInt(3, longestBacktickRun(ex.Code)+1))
	// The language tag sits on the opening fence line, and it is one word:
	// take the first, so a newline or a backtick in a model-supplied value
	// cannot break out of the block.
	lang := ""
	if fields := strings.Fields(strings.ReplaceAll(ex.Language, "`", " ")); len(fields) > 0 {
		lang = fields[0]
	}
	// A trailing newline in the code would otherwise double up before the
	// closing fence.
	return fence + lang + "\n" + strings.TrimRight(ex.Code, "\n") + "\n" + fence + "\n"
}

// longestBacktickRun returns the length of the longest consecutive run of
// backticks in s.
func longestBacktickRun(s string) int {
	longest, run := 0, 0
	for _, r := range s {
		if r == '`' {
			run++
			if run > longest {
				longest = run
			}
		} else {
			run = 0
		}
	}
	return longest
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func effectiveDoExamples(r state.Rule) []state.Example {
	if len(r.DoExamples) > 0 {
		return r.DoExamples
	}
	if r.DoExample != nil {
		return []state.Example{*r.DoExample}
	}
	return nil
}

func effectiveDontExamples(r state.Rule) []state.Example {
	if len(r.DontExamples) > 0 {
		return r.DontExamples
	}
	if r.DontExample != nil {
		return []state.Example{*r.DontExample}
	}
	return nil
}

// approvedRules returns approved rules for a given target location,
// sorted stated → established → emerging, then alphabetically by title.
func approvedRules(s state.State, location string) []state.Rule {
	var out []state.Rule
	for _, r := range s.Rules {
		if r.Status == "approved" && r.Target.Location == location {
			out = append(out, r)
		}
	}
	sortRules(out)
	return out
}

// confidenceRank returns the sort priority for a confidence level.
// Lower is higher priority: stated(0) > established(1) > emerging(2).
func confidenceRank(c string) int {
	switch c {
	case "stated":
		return 0
	case "established":
		return 1
	case "emerging":
		return 2
	default:
		return 3
	}
}

// sourceLabel returns the provenance text for a rule's "_Source: …_" line.
// Manual, discover and code-review origin rules have no PR numbers, so they
// get a descriptive label instead of an empty PR list.
func sourceLabel(r state.Rule) string {
	// Whatever a rule's origin, review corroboration it later absorbed through
	// Step 8C is part of its provenance. Every branch here once dropped it:
	// pr-review rendered the review signal as "PR #0", code-review dropped the
	// PRs, and manual and discover said nothing at all — presenting a rule two
	// reviewers had since confirmed as though no reviewer had ever seen it.
	reviewed := ""
	if tools := reviewerNames(reviewSources(r.Sources)); tools != "" {
		reviewed = " and code review (" + tools + ")"
	} else if hasReviewSource(r.Sources) {
		reviewed = " and code review"
	}

	switch r.Origin {
	case "manual":
		return "manually added" + reviewed
	case "discover":
		return "discovered from codebase" + reviewed
	case "code-review":
		// Name the reviewers: which tool flagged a convention is what tells a
		// reader whether to trust it, and two different tools agreeing is a
		// stronger claim than one repeating itself. Only the review sources
		// are named — a code-review rule can later absorb a PR signal through
		// Step 8C, and listing that human's login among the tools would
		// present them as one, while dropping their PR from the citation.
		label := strings.TrimPrefix(reviewed, " and ")
		if label == "" {
			label = "code review"
		}
		if prs := prList(r.Sources); prs != "" {
			label += " and PRs " + prs
		}
		return label
	default:
		// A PR-origin rule can hold review signals too: Step 8C merges an
		// equivalent review candidate into the existing rule and keeps that
		// rule's origin. Those sources carry pr_number 0, which prList used to
		// render as "PR #0" — a citation to a pull request that does not
		// exist, on exactly the rules the review path is meant to strengthen.
		prs := prList(r.Sources)
		switch {
		case prs != "":
			return "PRs " + prs + reviewed
		case reviewed != "":
			return strings.TrimPrefix(reviewed, " and ")
		}
		return "—"
	}
}

// hasReviewSource reports whether any signal was mined from a captured review.
func hasReviewSource(sources []state.Signal) bool {
	for _, s := range sources {
		if s.ReviewID != "" {
			return true
		}
	}
	return false
}

// reviewSources returns just the signals mined from captured reviews.
func reviewSources(sources []state.Signal) []state.Signal {
	var out []state.Signal
	for _, s := range sources {
		if s.ReviewID != "" {
			out = append(out, s)
		}
	}
	return out
}

// reviewerNames lists the distinct reviewers behind a rule, for the source
// line of a rule mined from watched code-review output, where the reviewer is
// the tool's name. Capped so a convention flagged by many tools does not push
// a source line past a readable length.
func reviewerNames(sources []state.Signal) string {
	seen := map[string]bool{}
	var names []string
	for _, s := range sources {
		name := strings.TrimSpace(s.Reviewer)
		if name == "" || seen[name] {
			continue
		}
		seen[name] = true
		names = append(names, name)
	}
	sort.Strings(names)
	const maxNames = 3
	if len(names) > maxNames {
		return strings.Join(names[:maxNames], ", ") + ", …"
	}
	return strings.Join(names, ", ")
}

// prList renders the distinct PRs behind a rule. Signals with no PR — a
// merged review signal, a manual one — contribute nothing rather than a
// "#0" citation.
func prList(sources []state.Signal) string {
	seen := map[int]bool{}
	var nums []int
	for _, s := range sources {
		if s.PRNumber <= 0 {
			continue
		}
		if !seen[s.PRNumber] {
			seen[s.PRNumber] = true
			nums = append(nums, s.PRNumber)
		}
	}
	sort.Ints(nums)
	parts := make([]string, len(nums))
	for i, n := range nums {
		parts[i] = fmt.Sprintf("#%d", n)
	}
	return strings.Join(parts, ", ")
}

// exemplaryFiles returns up to 3 file paths that appear most frequently as
// FileRef targets across the domain's rules. These are the files that best
// represent the domain's coding style and are listed in the skill file so
// the AI can read one for holistic style guidance beyond individual rules.
func exemplaryFiles(rules []state.Rule) []string {
	freq := map[string]int{}
	for _, r := range rules {
		for _, ex := range effectiveDoExamples(r) {
			if ex.FileRef == "" {
				continue
			}
			// Strip :Lline suffix to get the bare file path.
			path := ex.FileRef
			if idx := strings.LastIndex(path, ":L"); idx > 0 {
				path = path[:idx]
			}
			freq[path]++
		}
	}
	if len(freq) == 0 {
		return nil
	}

	type entry struct {
		path  string
		count int
	}
	var entries []entry
	for p, c := range freq {
		entries = append(entries, entry{p, c})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].count != entries[j].count {
			return entries[i].count > entries[j].count
		}
		return entries[i].path < entries[j].path
	})

	max := 3
	if len(entries) < max {
		max = len(entries)
	}
	out := make([]string, max)
	for i := range out {
		out[i] = entries[i].path
	}
	return out
}

// collectGlobs gathers the distinct, non-empty file globs across rules, with
// brace groups expanded. The frontmatter `paths` field is one comma-separated
// string, so a glob that itself contains a comma ("src/{a,b}/**/*.go") would
// be split by the consumer into two broken globs; expanding the group into
// plain globs keeps every comma out of the value. A glob that still carries a
// comma after expansion cannot be represented: silently dropping it would
// widen (or remove) the skill's paths gate, so it is an error instead.
func collectGlobs(rules []state.Rule) ([]string, error) {
	var all []string
	for _, r := range rules {
		for _, g := range r.Target.FileGlob {
			if g == "" {
				continue
			}
			expanded, err := ExpandBraces(g)
			if err != nil {
				return nil, fmt.Errorf("file glob %q: %w", g, err)
			}
			for _, e := range expanded {
				if strings.Contains(e, ",") {
					return nil, fmt.Errorf("file glob %q contains a comma, which the skill's comma-separated paths field cannot carry; rewrite the glob without it (brace groups such as {a,b} are expanded automatically) and rerun", g)
				}
				// A paths gate is repository-relative; a glob that climbs
				// out of the repository can never match a file the skill
				// should load for.
				if EscapesRoot(e) {
					return nil, fmt.Errorf("file glob %q points outside the repository, which a paths gate cannot express; use a repository-relative glob and rerun", g)
				}
				all = append(all, e)
			}
		}
	}
	return DedupeStrings(all), nil
}

// ExpandBraces expands every {a,b,...} group in glob, nested and successive
// groups included. It is the one brace parser for rule file globs: the
// frontmatter paths gate and the example anchoring in the CLI both go
// through it, so a glob means the same thing in both, and it is where a
// malformed group is diagnosed: an unbalanced brace, or an empty alternative
// ("{a,}", "{,a}", "{}" — the shell idiom for "or nothing", which a paths
// gate cannot express and which would emit a glob matching nothing).
func ExpandBraces(glob string) ([]string, error) {
	open, depth := -1, 0
	for i := 0; i < len(glob); i++ {
		switch glob[i] {
		case '\\':
			// An escaped character is literal, as path.Match reads it.
			i++
		case '[':
			// A character class may legitimately contain braces
			// ("[{}]"); skip to its end so they are not read as a group.
			if end := classEnd(glob, i); end > i {
				i = end
			}
		case '{':
			if depth == 0 {
				open = i
			}
			depth++
		case '}':
			if depth == 0 {
				return nil, errUnbalancedBrace
			}
			depth--
			if depth == 0 {
				var out []string
				for _, alt := range splitTopLevel(glob[open+1 : i]) {
					if alt == "" {
						return nil, errEmptyAlternative
					}
					sub, err := ExpandBraces(glob[:open] + alt + glob[i+1:])
					if err != nil {
						return nil, err
					}
					out = append(out, sub...)
				}
				return out, nil
			}
		}
	}
	if depth != 0 {
		return nil, errUnbalancedBrace
	}
	return []string{glob}, nil
}

var (
	errUnbalancedBrace  = fmt.Errorf("has an unbalanced brace; close every {a,b} group (or remove the stray brace) and rerun")
	errEmptyAlternative = fmt.Errorf("has an empty brace alternative, which a paths gate cannot express; list the alternatives explicitly and rerun")
)

// classEnd returns the index of the ']' closing the character class that
// opens at s[open], or -1 when the class is not closed (in which case the
// '[' is an ordinary character, as path.Match treats it).
func classEnd(s string, open int) int {
	i := open + 1
	if i < len(s) && (s[i] == '^' || s[i] == '!') {
		i++
	}
	if i < len(s) && s[i] == ']' {
		i++ // a leading ']' is a literal member
	}
	for ; i < len(s); i++ {
		switch s[i] {
		case '\\':
			i++
		case ']':
			return i
		}
	}
	return -1
}

// splitTopLevel splits s on commas that are not inside a nested brace group
// or a character class.
func splitTopLevel(s string) []string {
	var parts []string
	depth, start := 0, 0
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '\\':
			i++
		case '[':
			if end := classEnd(s, i); end > i {
				i = end
			}
		case '{':
			depth++
		case '}':
			depth--
		case ',':
			if depth == 0 {
				parts = append(parts, s[start:i])
				start = i + 1
			}
		}
	}
	return append(parts, s[start:])
}

// buildDescription returns the SKILL.md frontmatter description for a domain.
// If override is non-empty, it is used directly (truncated if needed). Otherwise
// a generic fallback is constructed from the domain name and globs.
func buildDescription(domain string, globs []string, universal bool, override string) string {
	// The override is model-supplied; a newline would break the YAML
	// frontmatter line it is rendered into, and a whitespace-only value is
	// no description at all.
	if override = strings.Join(strings.Fields(override), " "); override != "" {
		return truncate(override, maxDescriptionRunes)
	}
	if universal {
		return "Repo-wide coding conventions extracted from PR review history. Applies to every file; read before writing or reviewing code anywhere in this repository."
	}
	base := fmt.Sprintf("Coding conventions for %s", domain)
	if len(globs) > 0 {
		base += fmt.Sprintf(". Use when editing files matching: %s", strings.Join(globs, ", "))
	}
	return truncate(base, maxDescriptionRunes)
}

// maxDescriptionRunes caps the frontmatter description. Counted in runes,
// not bytes: descriptions routinely carry em dashes and similar multi-byte
// characters, and a byte-indexed cut can split one and leave invalid UTF-8
// in the YAML.
const maxDescriptionRunes = 200

// truncate shortens s to at most max runes, ending in "..." when it cut.
func truncate(s string, max int) string {
	r := []rune(s)
	if len(r) <= max {
		return s
	}
	return strings.TrimRight(string(r[:max-3]), " ") + "..."
}

// validDomain reports whether a domain name can be used as a single skill
// directory segment on every platform. Domain names are model-supplied; one
// containing a path separator or "." / ".." would write outside
// <skillsDir>/<domain>, and one the operating system rejects (over-long,
// control characters, the characters Windows forbids in file names) would
// fail mid-run after other skills were written. Charset rules for skill
// names (lowercase, digits, hyphens) are the audit-format subcommand's job
// and are deliberately not enforced here.
func validDomain(domain string) bool {
	if domain == "" || domain == "." || domain == ".." {
		return false
	}
	// The longest name actually created is the staging sibling, tail
	// included.
	if len(domain)+transientExtraBytes > maxDomainBytes {
		return false
	}
	for _, r := range domain {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	if strings.ContainsAny(domain, `/\<>:"|?*`) {
		return false
	}
	// A name carrying one of the transient-directory suffixes would be
	// mistaken for a leftover of an interrupted swap and cleared.
	if isTransientDir(domain) {
		return false
	}
	// Windows: a trailing dot or space is stripped by the filesystem, and
	// the legacy device names are reserved whatever extension follows.
	if strings.HasSuffix(domain, ".") || strings.HasSuffix(domain, " ") {
		return false
	}
	base := strings.ToLower(domain)
	if dot := strings.Index(base, "."); dot >= 0 {
		base = base[:dot]
	}
	return !windowsReservedNames[base]
}

// maxDomainBytes is the file-name length limit common to the major
// filesystems (255 bytes), which every directory segment written for a
// domain (the domain itself and its transient siblings) must respect.
const maxDomainBytes = 255

var windowsReservedNames = map[string]bool{
	"con": true, "prn": true, "aux": true, "nul": true,
	"com1": true, "com2": true, "com3": true, "com4": true, "com5": true,
	"com6": true, "com7": true, "com8": true, "com9": true,
	"lpt1": true, "lpt2": true, "lpt3": true, "lpt4": true, "lpt5": true,
	"lpt6": true, "lpt7": true, "lpt8": true, "lpt9": true,
}

// yamlQuote renders s as a YAML double-quoted scalar. It is strconv.Quote:
// every escape Go emits (\a \b \f \n \r \t \v \\ \" \xNN \uNNNN \UNNNNNNNN)
// is also a YAML double-quoted escape, and Go escapes everything that is not
// printable — the C0/C1 controls a YAML parser rejects raw, and the line
// separators (U+0085, U+2028, U+2029) a parser would otherwise fold together
// with adjacent whitespace. Invalid UTF-8 is escaped byte-wise rather than
// passed through.
func yamlQuote(s string) string {
	return strconv.Quote(s)
}

// capitalize upper-cases the first rune of s (not the first byte, which would
// corrupt a leading multi-byte character).
func capitalize(s string) string {
	r, size := utf8.DecodeRuneInString(s)
	if size == 0 || r == utf8.RuneError {
		return s
	}
	return string(unicode.ToUpper(r)) + s[size:]
}

// initialisms maps domain words to their conventional heading spelling.
// Anything not listed is simply capitalized; the list only needs to cover
// the common cases so "Api Conventions" does not read as a typo. Numeronyms
// keep their customary lower-case form.
var initialisms = map[string]string{
	"api": "API", "db": "DB", "sql": "SQL", "http": "HTTP", "rest": "REST", "grpc": "gRPC",
	"rpc": "RPC", "ui": "UI", "ux": "UX", "cli": "CLI", "css": "CSS", "html": "HTML",
	"js": "JS", "ts": "TS", "orm": "ORM", "dto": "DTO", "jwt": "JWT", "sdk": "SDK",
	"ci": "CI", "cd": "CD", "io": "IO", "id": "ID", "sso": "SSO", "oauth": "OAuth",
	"ssr": "SSR", "i18n": "i18n", "l10n": "l10n", "k8s": "k8s", "aws": "AWS", "gcp": "GCP",
}

// headingTitle turns a domain slug into heading text: hyphens and
// underscores become spaces, known initialisms take their conventional
// spelling ("rest-api" → "REST API"), everything else is capitalized
// ("components" → "Components").
func headingTitle(domain string) string {
	words := strings.FieldsFunc(domain, func(r rune) bool { return r == '-' || r == '_' })
	if len(words) == 0 {
		return domain
	}
	for i, w := range words {
		if canonical, ok := initialisms[strings.ToLower(w)]; ok {
			words[i] = canonical
		} else {
			words[i] = capitalize(w)
		}
	}
	return strings.Join(words, " ")
}

// tmpPath is the temp file atomicWrite stages path's content in. It is a
// helper rather than an inline literal because isEmptyDir must recognise
// the leftover of an interrupted pre-staging write by the same name.
func tmpPath(path string) string {
	return path + ".tmp"
}

func atomicWrite(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp := tmpPath(path)
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
